$ANSIBLE_VAULT;1.1;AES256
39373565623365613161313539373266333361653034396436636464316461333637386334313062
3964663865643833343135366236323563623962646439380a613933666531373432656434353639
34326435323564383637326430646261383664653061646539363631306331656462336137353536
3230643632306531650a663736346161366365346436626366376238313932333736353137653037
63303237356561363263636261643439306233373435336666666233313230353133666335613332
35633063333532623661623536363437396365323166376366336166323033303766313136643933
37373538326538626131313435316333306134396537376331363031363134636261333238656661
34343763346638366537663932633061623930313436616664383031366663316137653334333362
36383335613635663561653438633266626134616638373239336566616364306461336362323663
37303734376365373233323137656464386539346336323330383761323964363237613538653831
35353666333437373961396364663036373839396135613537666464326162613536376536383739
63326139383035353064636234623337373865636333376239353239613531306537613662323938
66336532393231336138643031366261306631656634333038623535353638373032346637383565
30393231353631656437626230393832633533343666646535343837666564663637333836386636
38333962306333613561646665646132313163376334346235626434376433653037346563303931
35393135393730663265363132303834333264383434366132326637316638303936633330666232
31653864366135346330393233316665393331393561373963643639626564643536626164366633
37646630306230303866373961313365363437656563656133623464373035383964343739303762
323365633465643336343639396537663666
